version: "3.9"
services:
  rabbitmq:
    container_name: ${PROJECT_NAME:-project}-rabbitmq
    image: ${RABBITMQ_TAG:-bitnami/rabbitmq:latest}
    depends_on:
      - database

  web-service:
    container_name: ${PROJECT_NAME:-project}-web-service
    image: ${WEB_SERVICE_TAG:-egalbox/web-service:2.4.0}
    restart: on-failure
    depends_on:
      - database
      - rabbitmq

  database:
    container_name: ${PROJECT_NAME:-project}-database
    image: ${DATABASE_TAG:-egalbox/postgres:2.4.0}
    restart: unless-stopped

  core-service:
    container_name: ${PROJECT_NAME:-project}-core-service
    build: ../project
    tty: true
    restart: on-failure
    depends_on:
      - web-service

  adminer:
    container_name: ${PROJECT_NAME:-project}-adminer
    image: adminer
    restart: always
    depends_on:
      - database


